src/api/urls.py
from django.conf.urls import url

from api import views

urlpatterns = [
	url(r'^delete', views.queue_delete, name='queue_delete'),
	url(r'^enrich', views.queue_enrich, name='queue_enrich'),
	url(r'^index-web', views.queue_index_web, name='queue_index_web'),
	url(r'^index-rss', views.queue_index_rss, name='queue_index_rss'),
	url(r'^index-file', views.queue_index_file, name='queue_index_file'),
	url(r'^index-filedirectory', views.queue_index_file, name='queue_index_filedirectory'),
	url(r'^index-dir', views.queue_index_file, name='queue_index_dir'),
]

src/opensemanticsearch/urls.py
from django.conf.urls import include, url

from django.contrib import admin

from django.contrib import auth

from django.urls import path


urlpatterns = [
	path('admin/', admin.site.urls),
	url(r'^api/', include(('api.urls', 'api'), namespace="api")),
	url(r'^entity_rest_api/', include(('entity_rest_api.urls', 'entity_rest_api'), namespace="entity_rest_api")),
	url(r'^setup/', include(('setup.urls', 'setup'), namespace="setup")),
	url(r'^crawler/', include(('crawler.urls', 'crawler'), namespace="crawler")),
	url(r'^files/', include(('files.urls', 'files'), namespace="files")),
	url(r'^datasources/', include(('datasources.urls', 'datasources'), namespace="datasources")),
	url(r'^annotate/', include(('annotate.urls', 'annotate'), namespace="annotate")),
	url(r'^thesaurus/', include(('thesaurus.urls', 'thesaurus'), namespace="thesaurus")),
	url(r'^rss_manager/', include(('rss_manager.urls', 'rss_manager'), namespace="rss_manager")),
	url(r'^querytagger/', include(('querytagger.urls', 'querytagger'), namespace="querytagger")),
	url(r'^search-list/', include(('search_list.urls', 'search_list'), namespace="search_list")),
	url(r'^csv/', include(('csv_manager.urls', 'csv_manager'), namespace="csv_manager")),
	url(r'^ontologies/', include(('ontologies.urls', 'ontologies'), namespace="ontologies")),
	url(r'^hypothesis/', include(('hypothesis.urls', 'hypothesis'), namespace="hypothesis")),
	url(r'^graph/', include(('visual_graph_explorer.urls', 'visual_graph_explorer'), namespace="graph")),
	url(r'^search_entity/', include(('search_entity.urls', 'search_entity'), namespace="search_entity")),
	url(r'^morphology/', include(('morphology.urls', 'morphology'), namespace="morphology")),
	url(r'^twitter/', include(('twitter.urls', 'twitter'), namespace="twitter")),
]

src/setup/urls.py
from django.conf.urls import url

from setup import views

urlpatterns = [
	url(r'^$', views.update_setup, name='index'),
	url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
	url(r'^(?P<pk>\d+)/update$', views.update_setup, name='update'),
]

src/setup/models.py
from django.db import models

class Setup(models.Model):

	title = models.CharField(max_length=1000, blank=True)
	description = models.TextField(blank=True)

	language = models.CharField(max_length=2, default="en", blank=True)

	languages = models.CharField(max_length=300, default="en", blank=True)
	languages_force = models.CharField(max_length=300, default="en", blank=True)

	languages_hunspell = models.CharField(max_length=300, default="hu", blank=True)
	languages_force_hunspell = models.CharField(max_length=300, default="", blank=True)
	
	ocr = models.BooleanField(default=True)
	ocr_later = models.BooleanField(default=True)

	ocr_languages = models.CharField(max_length=300, default="eng", blank=True)

	ocr_descew = models.BooleanField(default=False)

	ocr_pdf = models.BooleanField(default=True)
	
	ner_spacy = models.BooleanField(default=True)

	ner_stanford = models.BooleanField(default=False)

	segmentation_pages = models.BooleanField(default=False)
	segmentation_pages_preview = models.BooleanField(default=False)

	segmentation_sentences = models.BooleanField(default=False)

	graph_neo4j = models.BooleanField(default=False)
	graph_neo4j_host = models.CharField(max_length=1000, blank=True)
	graph_neo4j_user = models.CharField(max_length=1000, blank=True)
	graph_neo4j_password = models.CharField(max_length=1000, blank=True)
	graph_neo4j_browser = models.CharField(max_length=1000, blank=True)

	url_tasks = models.CharField(max_length=1000, blank=True, default="http://localhost:5555/tasks")

src/setup/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponse
from django.template import RequestContext
from django.views import generic
from django.forms import ModelForm
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.utils import timezone
from django import forms


from setup.models import Setup
from ontologies.models import Ontologies


# Language of UI
LANGUAGE_CHOICES = (
	('en', 'English'),
	('ar', 'Arabic'),
	('de', 'Deutsch (German)'),
	('it', 'Italian'),
	('pt', 'Portuguese'),
	('fr', 'French (Switzerland)')
)


# Grammar / Stemming languages
LANGUAGES_CHOICES = (
	('en', 'English'),
	('ar', 'Arabic'),
	('cz', 'Czech'),
	('de', 'Deutsch (German)'),
	('fa', 'Farsi (Persian)'),
	('fr', 'Francais (French)'),
	('hu', 'Hungarian'),
	('it', 'Italian'),
	('nl', 'Dutch (Netherlands)'),
	('pt', 'Portuguese'),
	('ro', 'Romanian'),
	('ru', 'Russian'),
)

LANGUAGES_CHOICES_HUNSPELL = (
	('hu', 'Hungarian'),
)


# OCR dictionaries
OCR_LANGUAGES_CHOICES = (
	('Arabic', 'data for Arabic script'),
	('Armenian', 'data for Armenian script'),
	('Bengali', 'data for Bengali script'),
	('Canadian_Aboriginal', 'data for Canadian Aboriginal script'),
	('Cherokee', 'data for Cherokee script'),
	('Cyrillic', 'data for Cyrillic script'),
	('Devanagari', 'data for Devanagari script'),
	('Ethiopic', 'data for Ethiopic script'),
	('Fraktur', 'data for Fraktur script'),
	('Georgian', 'data for Georgian script'),
	('Greek', 'data for Greek script'),
	('Gujarati', 'data for Gujarati script'),
	('Gurmukhi', 'data for Gurmukhi script'),
	('Hangul', 'data for Hangul script'),
	('Hangul_vert', 'data for Hangul (vertical) script'),
	('HanS', 'data for Han - Simplified script'),
	('HanS_vert', 'data for Han - Simplified (vertical) script'),
	('HanT', 'data for Han - Traditional script'),
	('HanT_vert', 'data for Han - Traditional (vertical) script'),
	('Hebrew', 'data for Hebrew script'),
	('Japanese', 'data for Japanese script'),
	('Japanese_vert', 'data for Japanese (vertical) script'),
	('Khmer', 'data for Khmer script'),
	('Kannada', 'data for Kannada script'),
	('Lao', 'data for Lao script'),
	('Latin', 'data for Latin script'),
	('Malayalam', 'data for Malayalam script'),
	('Myanmar', 'data for Myanmar script'),
	('Oriya', 'data for Oriya (Odia) script'),
	('Sinhala', 'data for Sinhala script'),
	('Syriac', 'data for Syriac script'),
	('Tamil', 'data for Tamil script'),
	('Telugu', 'data for Telugu script'),
	('Thaana', 'data for Thaana script'),
	('Thai', 'data for Thai script'),
	('Tibetan', 'data for Tibetan script'),
	('Vietnamese', 'data for Vietnamese script'),
	('afr', 'Afrikaans'),
	('amh', 'Amharic'),
	('ara', 'Arabic'),
	('asm', 'Assamese'),
	('aze', 'Azerbaijani'),
	('aze_cyrl', 'Azerbaijani (Cyrillic)'),
	('bel', 'Belarusian'),
	('ben', 'Bengali'),
	('bod', 'Tibetan Standard'),
	('bos', 'Bosnian'),
	('bul', 'Bulgarian'),
	('cat', 'Catalan'),
	('ceb', 'Cebuano'),
	('ces', 'Czech'),
	('chi_sim', 'Chinese  - Simplified'),
	('chi_sim_vert', 'Chinese - Simplified (vertical)'),
	('chi_tra', 'Chinese - Traditional'),
	('chi_tra_vert', 'Chinese - Traditional (vertical)'),
	('chr', 'Cherokee'),
	('cos', 'Corsican'),
	('cym', 'Welsh'),
	('dan', 'Danish'),
	('deu', 'German'),
	('div', 'Divehi'),
	('dzo', 'Dzongkha'),
	('ell', 'Greek'),
	('eng', 'English'),
	('enm', 'English, Middle (1100-1500)'),
	('epo', 'Esperanto'),
	('est', 'Estonian'),
	('eus', 'Basque'),
	('fao', 'Faroese'),
	('fas', 'Persian'),
	('fil', 'Filipino'),
	('fin', 'Finnish'),
	('fra', 'French'),
	('frk', 'German (Fraktur)'),
	('frm', 'French, Middle (ca.1400-1600)'),
	('fry', 'Frisian (Western)'),
	('gla', 'Gaelic (Scots)'),
	('gle', 'Irish'),
	('glg', 'Galician'),
	('guj', 'Gujarati'),
	('hat', 'Hatian'),
	('heb', 'Hebrew'),
	('hin', 'Hindi'),
	('hrv', 'Croatian'),
	('hun', 'Hungarian'),
	('hye', 'Armenian'),
	('iku', 'Inuktitut'),
	('ind', 'Indonesian'),
	('isl', 'Icelandic'),
	('ita', 'Italian'),
	('ita_old', 'Italian - Old'),
	('jav', 'Javanese'),
	('jpn', 'Japanese'),
	('jpn_vert', 'Japanese (vertical)'),
	('kan', 'Kannada'),
	('kat', 'Georgian'),
	('kat_old', 'Old Georgian'),
	('kaz', 'Kazakh'),
	('khm', 'Khmer'),
	('kir', 'Kyrgyz'),
	('kor', 'Korean'),
	('kor_vert', 'Korean (vertical)'),
	('kur_ara', 'Kurdish (Arabic)'),
	('lao', 'Lao'),
	('lat', 'Latin'),
	('lav', 'Latvian'),
	('lit', 'Lithuanian'),
	('ltz', 'Luxembourgish'),
	('mal', 'Malayalam'),
	('mar', 'Marathi'),
	('mkd', 'Macedonian'),
	('mlt', 'Maltese'),
	('mon', 'Mongolian'),
	('mri', 'Maori'),
	('msa', 'Malay'),
	('mya', 'Burmese'),
	('nep', 'Nepali'),
	('nld', 'Dutch'),
	('nor', 'Norwegian'),
	('oci', 'Occitan (post 1500)'),
	('ori', 'Oriya'),
	('osd', 'script and orientation'),
	('pan', 'Punjabi'),
	('pol', 'Polish'),
	('por', 'Portuguese'),
	('pus', 'Pashto'),
	('que', 'Quechua'),
	('ron', 'Romanian'),
	('rus', 'Russian'),
	('san', 'Sanskrit'),
	('sin', 'Sinhala'),
	('slk', 'Slovak'),
	('slv', 'Slovenian'),
	('snd', 'Sindhi'),
	('spa', 'Spanish'),
	('spa_old', 'Spanish, Castilian - Old'),
	('sqi', 'Albanian'),
	('srp', 'Serbian'),
	('srp_latn', 'Serbian (Latin)'),
	('sun', 'Sudanese'),
	('swa', 'Swahili'),
	('swe', 'Swedish'),
	('syr', 'Syriac'),
	('tam', 'Tamil'),
	('tat', 'Tatar'),
	('tel', 'Telugu'),
	('tgk', 'Tajik'),
	('tha', 'Thai'),
	('tir', 'Tigrinya'),
	('ton', 'Tonga'),
	('tur', 'Turkish'),
	('uig', 'Uyghur'),
	('ukr', 'Ukranian'),
	('urd', 'Urdu'),
	('uzb', 'Uzbek'),
	('uzb_cyrl', 'Uzbek (Cyrillic)'),
	('vie', 'Vietnamese'),
	('yid', 'Yiddish'),
	('yor', 'Yoruba'),
)


class SetupForm(ModelForm):

	class Meta:
		model = Setup
		exclude = ['language', 'languages', 'languages_force', 'languages_hunspell', 'languages_force_hunspell', 'ocr_languages']

		
	language = forms.ChoiceField(
		required=False,
		choices=LANGUAGE_CHOICES,
    )
		
	languages = forms.MultipleChoiceField(
		required=False,
		widget=forms.CheckboxSelectMultiple,
		choices=LANGUAGES_CHOICES,
    )

	languages_force = forms.MultipleChoiceField(
		required=False,
		widget=forms.CheckboxSelectMultiple,
		choices=LANGUAGES_CHOICES,
    )

	languages_hunspell = forms.MultipleChoiceField(
		required=False,
		widget=forms.CheckboxSelectMultiple,
		choices=LANGUAGES_CHOICES_HUNSPELL,
    )

	languages_force_hunspell = forms.MultipleChoiceField(
		required=False,
		widget=forms.CheckboxSelectMultiple,
		choices=LANGUAGES_CHOICES_HUNSPELL,
    )

	ocr_languages = forms.MultipleChoiceField(
		required=False,
		widget=forms.CheckboxSelectMultiple,
		choices=OCR_LANGUAGES_CHOICES,
    )

class IndexView(generic.ListView):
	model = Setup

class DetailView(generic.DetailView):
	model = Setup

class UpdateView(generic.UpdateView):
	model = Setup


#
# Write setup from database to Open Semantic ETL config file
#
def	generate_etl_configfile(filename="/etc/opensemanticsearch/etl-webadmin"):

	setup = Setup.objects.get(pk=1)

	configfile = open(filename, "w", encoding="utf-8")

	configfile.write( "# Warning: Do not edit here, will be overwritten by the web admin user interface\n" )

	if setup.languages:
		languages = setup.languages.split(',')
	else:
		languages = []

	configfile.write( "config['languages'] = " + str(languages) + "\n" )

	if setup.languages_force:
		languages_force = setup.languages_force.split(',')
	else:
		languages_force = []

	configfile.write( "config['languages_force'] = " +  str(languages_force) + "\n" )

	if setup.languages_hunspell:
		languages_hunspell = setup.languages_hunspell.split(',')
	else:
		languages_hunspell = []

	configfile.write( "config['languages_hunspell'] = " + str(languages_hunspell) + "\n" )

	if setup.languages_force_hunspell:
		languages_force_hunspell = setup.languages_force_hunspell.split(',')
	else:
		languages_force_hunspell = []

	configfile.write( "config['languages_force_hunspell'] = " +  str(languages_force_hunspell) + "\n" )

	configfile.write( "config['ocr_lang'] = \'" + "+".join(setup.ocr_languages.split(',')) + "\'\n" )

	if setup.ocr_later and (setup.ocr or setup.ocr_pdf):
		# initialize (yet empty) config options for running plugins later, which will be set/appended there in further steps
		configfile.write( "if not 'additional_plugins_later' in config:\n" )
		configfile.write( "\tconfig['additional_plugins_later'] = []" + "\n" )
		configfile.write( "if not 'additional_plugins_later_config' in config:\n" )
		configfile.write( "\tconfig['additional_plugins_later_config'] = {}" + "\n" )
		

	if setup.ocr:

		if setup.ocr_later:
			configfile.write( "config['ocr'] = False\n" )
			configfile.write( "config['additional_plugins_later_config']['ocr'] = True\n" )
		else:
			configfile.write( "config['ocr'] = True\n" )
			
	else:
		configfile.write( "config['ocr'] = False\n" )
		
	if setup.ocr_pdf:

		if setup.ocr_later:
			configfile.write( "if 'enhance_pdf_ocr' in config['plugins']:" + "\n" )
			configfile.write( "\tconfig['plugins'].remove('enhance_pdf_ocr')" + "\n" )
			configfile.write( "if not 'enhance_pdf_ocr' in config['additional_plugins_later']:" + "\n" )
			configfile.write( "\tconfig['additional_plugins_later'].append('enhance_pdf_ocr')" + "\n" )
			
		else:
			configfile.write( "if not 'enhance_pdf_ocr' in config['plugins']:" + "\n" )
			configfile.write( "\tconfig['plugins'].append('enhance_pdf_ocr')" + "\n" )

	else:
		configfile.write( "if 'enhance_pdf_ocr' in config['plugins']:" + "\n" )
		configfile.write( "\tconfig['plugins'].remove('enhance_pdf_ocr')" + "\n" )

	if setup.ner_spacy:
		configfile.write( "if not 'enhance_ner_spacy' in config['plugins']:" + "\n" )
		configfile.write( "\tconfig['plugins'].append('enhance_ner_spacy')" + "\n" )
	else:
		configfile.write( "if 'enhance_ner_spacy' in config['plugins']:" + "\n" )
		configfile.write( "\tconfig['plugins'].remove('enhance_ner_spacy')" + "\n" )

	if setup.ner_stanford:
		configfile.write( "if not 'enhance_ner_stanford' in config['plugins']:" + "\n" )

src/setup/templates/setup/setup_form.html
{% extends "datasources_base.html" %}

{% block content %}

<form {% if form.is_multipart %}enctype="multipart/form-data"{% endif %} action="" method="post">{% csrf_token %}

    {{ form.non_field_errors }}

<div class="row">

	<div class="small-12 columns">


<h1>Edit setup</h1>


	</div>
</div>





<div class="row">

	<div class="small-12 columns">


<dl class="tabs" data-tab>
  <dd><a href="#panel-ui">Search user interface</a></dd>
  <dd class="active"><a href="#panel-language">Document language(s)</a></dd>
  <dd><a href="#panel-ocr">OCR</a></dd>
  <dd><a href="#panel-ner">Named Entity Recognition (NER)</a></dd>
  <dd><a href="#panel-segmentation">Segmentation (pages & sentences)</a></dd>
  <dd><a href="#panel-thumbnails">Preview (thumbnails)</a></dd>
  <dd><a href="#panel-neo4j">Graph DB (Neo4j)</a></dd>
  <dd><a href="#panel-servers">Servers (URLs)</a></dd>
</dl>

	</div>
</div>










<div class="tabs-content">

  <section class="content" id="panel-title">


<div class="row">
	<div class="small-12 columns text-center">
<h2>Name or notes</h2>
	</div>
</div>

<div class="row">
	<div class="small-12 columns">


<p>Not necessary, only for managing purpose</p>

        {{ form.title.errors }}
        <label for="id_title">Title:</label>
        {{ form.title }}

<div class="row">

    <div class="small-12 medium-8 columns">
    <h3>Notes</h3>
        {{ form.description.errors }}
        <label for="id_description">Description or Notes</label>
        {{ form.description }}
    </div>


</div>

</section>


  <section class="content" id="panel-ui">


<div class="row">
	<div class="small-12 columns text-center">
<h2>User interface</h2>
	</div>
</div>

<div class="row">

	<div class="small-12 columns text-center">

			{{ form.language.errors }}
			<label for="id_language">Language of search user interface:</label>
			{{ form.language }}

	</div>

</div>


</section>


  <section class="content active" id="panel-language">


<div class="row">
	<div class="small-12 columns text-center">
		<h2>Grammar (stemming)</h2>
	</div>
</div>

<div class="row">
			<p>You can enable all document language dependent grammars, since for each document only the grammar of the document language will be applied. If your documents are only or mainly in one language, you should force a grammar, so the grammar is applied even if the document language is not recognized correct.</p>

	<div class="small-6 columns text-center">

		
			<h3>Use grammar (dependent on document language)</h3>
			<p>Use grammar heuristic (stemming) if the document language was autodetected</p>

			{{ form.languages.errors }}
			<label for="id_languages">Grammars:</label>
			{{ form.languages }}

	</div>
	
	<div class="small-6 columns text-center">

			<h3>Force grammar (independent of document language)</h3>
			<p>Force grammar(s) / stemmers for all documents (even if other language)</p>

			{{ form.languages_force.errors }}
			<label for="id_languages_forced">Forced grammar(s):</label>
			{{ form.languages_force }}

	</div>
</div>

<div class="row">
			<p>Additional (results in bigger index) or alternate you can enable stemming by grammar rules and dictionary based Hunspell stemmer:</p>

	<div class="small-6 columns text-center">

		
			<h3>Use Hunspell stemmer (dependent on document language)</h3>
			<p>Use Hunspell rules & dictionary if the document language was autodetected</p>

			{{ form.languages_hunspell.errors }}
			<label for="id_languages_hunspell">Hunspell grammars:</label>
			{{ form.languages_hunspell }}

	</div>
	
	<div class="small-6 columns text-center">

			<h3>Force Hunspell stemmer (independent of document language)</h3>
			<p>Force Hunspell language rules & dictionaries for all documents (even if other language)</p>

			{{ form.languages_force_hunspell.errors }}
			<label for="id_languages_forced_hunspell">Forced hunspell grammar(s):</label>
			{{ form.languages_force_hunspell }}

	</div>
</div>

<div class="row">
	<div class="small-12 columns text-center">

		<h3>OCR dictionaries</h3>
		
			<p>Dictionaries to use for optical character recognition of scanned documents</p>


			{{ form.ocr_languages.errors }}
			<label for="id_ocr_languages">OCR dictionaries:</label>
			{{ form.ocr_languages }}



    </div>


</div>



</section>



  <section class="content" id="panel-ocr">


<div class="row">
	<div class="small-12 columns text-center">
<h2>OCR of scanned documents and images</h2>
	</div>
</div>

<div class="row">
	<div class="small-12 columns">


<p>Extract & find text from scanned or photographed documents by optical character recognition (OCR) of images</p>


<h3>OCR</h3>

<p>Extract text from images by optical character recognition</p>

        {{ form.ocr.errors }}
        <label for="id_ocr">OCR:</label>
        {{ form.ocr }}


<h3>OCR of images in PDF documents</h3>

<p>Extract text from images embedded in PDF documents (f.e. scanned documents)</p>

        {{ form.ocr_pdf.errors }}
        <label for="id_ocr_pdf">OCR images in PDF:</label>
        {{ form.ocr_pdf }}


<h3>Priority</h3>

        {{ form.ocr_later.errors }}
        <label for="id_ocr_later">Run configured OCR tasks later:</label>
        {{ form.ocr_later }}

<p>Since OCR slows down indexing by needing most time for often only few additional infos, OCR can be done later by reindexing with enabled OCR after all documents were yet indexed without OCR first to get an usable index many times faster. So you can search & will find most documents much earlier while OCR analysis runs later in background.</p>


<h3>OCR dictionaries</h3>

<p>Set up the used language specific OCR dictionaries in the tab <i>Document language(s)</i></p>

</div>

</section>


  <section class="content" id="panel-ner">


<div class="row">
	<div class="small-12 columns text-center">
<h2>Named Entity Recognition (NER) by machine learning</h2>
	</div>
</div>

<div class="row">
	<div class="small-12 columns">

<p>Named Entity recognition needs many CPU ressources while indexing documents, but will extract automatically many entities like persons, organizaztions or places (that are not configured in your thesaurus or ontologies) for interactive filters & enhanced analysis.</p>

<h3>SpaCy NER</h3>

<p>Extract named entities by SpaCy NER</p>

        {{ form.ner_spacy.errors }}
        <label for="id_ner_spacy">Spacy NER:</label>
        {{ form.ner_spacy }}


<h3>Stanford NER</h3>

<p>Alternate (or additionally to recognize some entities which SpaCy did not recognize) you can use the NER models of another NER framework Stanford NER</p>
        {{ form.ner_stanford.errors }}
        <label for="id_ner_stanford">Stanford NER:</label>
        {{ form.ner_stanford }}

<p>Warning: Low performance while indexing of documents!</p>

</div>

</section>



  <section class="content" id="panel-segmentation">


<div class="row">
	<div class="small-12 columns text-center">
<h2>Segmentation to pages</h2>
	</div>
</div>

<div class="row">
	<div class="small-12 columns">

<p>By segmentation of PDF files to single pages you can find and analyze PDF documents more granular by single pages.</p>

        {{ form.segmentation_pages.errors }}
        <label for="id_segmentation_pages">Segmentation to pages:</label>
        {{ form.segmentation_pages }}

<p>Warning: Will double indexing time and index size!</p>
</div>
</div>


<div class="row">
	<div class="small-12 columns text-center">

<h2>Segmentation to sentences</h2>
	</div>
</div>

<div class="row">
	<div class="small-12 columns">

<p>By segmentation of document text to single sentences you can find and analyze entities more granular by search and filter entities that occur together in same sentence(s).</p>

        {{ form.segmentation_sentences.errors }}
        <label for="id_segmentation_sentences">Sentence segmentation:</label>
        {{ form.segmentation_sentences }}

<p>Warning: Will double indexing time and index size!</p>


</div>
</div>

</section>



  <section class="content" id="panel-thumbnails">


<div class="row">
	<div class="small-12 columns text-center">
<h2>Preview (Thumbnails)</h2>
	</div>
</div>

<div class="row">
	<div class="small-12 columns">

<h3>PDF preview</h3>

<p>By additional segmentation / splitting of PDF files to single page PDF files for preview you can spare download bandwith for downloading of full PDF by only downloading/previewing the previewed pages, which can be useful outside your intranet providing search in very big/massive PDF documents over internet.</p>

        {{ form.segmentation_pages_preview.errors }}
        <label for="id_segmentation_pages_preview">Generate additional splitted / single page PDFs for preview:</label>
        {{ form.segmentation_pages_preview }}

<p>Warning: Needs additional disc space (more than the size of all indexed PDF files) in separate thumbnail directory!</p>

</div>

</section>



  <section class="content" id="panel-neo4j">


<div class="row">
	<div class="small-12 columns text-center">
<h2>Graph database (neo4j)</h2>
	</div>
</div>

<div class="row">
	<div class="small-12 columns">

<p>Export entities in documents and connections from/to documents to graph database for analysis and exploration of indirect connections.</p>

<h3>Export extracted entities and connections</h3>

<p>Export entities connections to Neo4j graph database</p>

        {{ form.graph_neo4j.errors }}
        <label for="id_graph_neo4j">Enable Neo4j plugin:</label>
        {{ form.graph_neo4j }}

<p><i>If you don't need analyze indirect connections since direct connections by faceted search are enough you can disable the plugin for performance issues.</i></p>

<h3>Neo4j server</h3>

        {{ form.graph_neo4j_host.errors }}
        <label for="id_graph_neo4j_host">Host:</label>
        {{ form.graph_neo4j_host }}

        {{ form.graph_neo4j_user.errors }}
        <label for="id_graph_neo4j_user">User:</label>
        {{ form.graph_neo4j_user }}

        {{ form.graph_neo4j_password.errors }}
        <label for="id_graph_neo4j_password">Password:</label>
        {{ form.graph_neo4j_password }}


<h3>Neo4j browser</h3>

<p>Links from search UI to Neo4j browser for exploration and visualization if the graph</p>

        {{ form.graph_neo4j_browser.errors }}
        <label for="id_graph_neo4j_browser">Neo4j browser URL:</label>
        {{ form.graph_neo4j_browser }}

</div>

</section>


  <section class="content" id="panel-servers">


<div class="row">
	<div class="small-12 columns text-center">
<h2>Servers (URLs)</h2>
	</div>
</div>

<div class="row">
	<div class="small-12 columns">

        {{ form.url_tasks.errors }}
        <label for="id_url_tasks">URL of Flower task monitoring UI:</label>
        {{ form.url_tasks }}

</div>

</section>


<hr>


<div class="row">
    <div class="small-12 columns">

<h2>Save changes</h2>

    <input class="button" type="submit" value="Save" />


    <a class="button" href="{% url 'setup:detail' setup.id %}">Cancel</a>

</div>
</div>

</form>
{% endblock content %}