src/api/urls.py
from django.conf.urls import url

from api import views

urlpatterns = [
	url(r'^delete', views.queue_delete, name='queue_delete'),
	url(r'^enrich', views.queue_enrich, name='queue_enrich'),
	url(r'^index-web', views.queue_index_web, name='queue_index_web'),
	url(r'^index-rss', views.queue_index_rss, name='queue_index_rss'),
	url(r'^index-file', views.queue_index_file, name='queue_index_file'),
	url(r'^index-filedirectory', views.queue_index_file, name='queue_index_filedirectory'),
	url(r'^index-dir', views.queue_index_file, name='queue_index_dir'),
]

src/opensemanticsearch/urls.py
from django.conf.urls import include, url

from django.contrib import admin

from django.contrib import auth

from django.urls import path


urlpatterns = [
	path('admin/', admin.site.urls),
	url(r'^api/', include(('api.urls', 'api'), namespace="api")),
	url(r'^entity_rest_api/', include(('entity_rest_api.urls', 'entity_rest_api'), namespace="entity_rest_api")),
	url(r'^setup/', include(('setup.urls', 'setup'), namespace="setup")),
	url(r'^crawler/', include(('crawler.urls', 'crawler'), namespace="crawler")),
	url(r'^files/', include(('files.urls', 'files'), namespace="files")),
	url(r'^datasources/', include(('datasources.urls', 'datasources'), namespace="datasources")),
	url(r'^annotate/', include(('annotate.urls', 'annotate'), namespace="annotate")),
	url(r'^thesaurus/', include(('thesaurus.urls', 'thesaurus'), namespace="thesaurus")),
	url(r'^rss_manager/', include(('rss_manager.urls', 'rss_manager'), namespace="rss_manager")),
	url(r'^querytagger/', include(('querytagger.urls', 'querytagger'), namespace="querytagger")),
	url(r'^search-list/', include(('search_list.urls', 'search_list'), namespace="search_list")),
	url(r'^csv/', include(('csv_manager.urls', 'csv_manager'), namespace="csv_manager")),
	url(r'^ontologies/', include(('ontologies.urls', 'ontologies'), namespace="ontologies")),
	url(r'^hypothesis/', include(('hypothesis.urls', 'hypothesis'), namespace="hypothesis")),
	url(r'^graph/', include(('visual_graph_explorer.urls', 'visual_graph_explorer'), namespace="graph")),
	url(r'^search_entity/', include(('search_entity.urls', 'search_entity'), namespace="search_entity")),
	url(r'^morphology/', include(('morphology.urls', 'morphology'), namespace="morphology")),
	url(r'^twitter/', include(('twitter.urls', 'twitter'), namespace="twitter")),
]

src/rss_manager/urls.py
from django.conf.urls import url

from rss_manager import views

urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
	url(r'^(?P<pk>\d+)/import$', views.import_feed, name='import_feed'),
	url(r'^(?P<pk>\d+)/delete$', views.delete, name='delete'),
	url(r'^import$', views.import_feeds, name='import_feeds'),
	url(r'^create$', views.create_feed, name='create'),
	url(r'^(?P<pk>\d+)/update$', views.update_feed, name='update'),
]

src/rss_manager/models.py
from django.db import models



class RSS_Feed(models.Model):

	uri = models.CharField(max_length=1000, blank=False)

	delta = models.IntegerField(default=60)
	
	title = models.CharField(max_length=1000, blank=True)

	description = models.TextField(blank=True)
	
	last_imported = models.DateTimeField(null=True, blank=True)
	


	def __str__(self):
		
		name = self.title
		
		if not name:
			name = self.uri

		if not name:
			name = self.id
	
		return name

src/rss_manager/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponse
from django.template import RequestContext
from django.views import generic
from django.forms import ModelForm
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.utils import timezone
from django.shortcuts import redirect

import datetime
from datetime import timedelta

from rss_manager.models import RSS_Feed


class RSSFeedForm(ModelForm):

	class Meta:
		model = RSS_Feed
		fields = '__all__'

class IndexView(generic.ListView):
	model = RSS_Feed

class DetailView(generic.DetailView):
	model = RSS_Feed

class CreateView(generic.CreateView):
	model = RSS_Feed

class UpdateView(generic.UpdateView):
	model = RSS_Feed


#
# New/additional feed
#

def create_feed(request):

	if request.method == 'POST':

		form = RSSFeedForm(request.POST, request.FILES)


		if form.is_valid():
			feed = form.save()

			return HttpResponseRedirect( reverse('rss_manager:detail', args=[feed.pk]) ) # Redirect after POST

	else:
		form = RSSFeedForm()

	return render(request, 'rss_manager/rss_feed_form.html', 
			{'form': form,	} )
	

#
# Updated an feed
#

def update_feed(request, pk):

	feed = RSS_Feed.objects.get(pk=pk)
	
	if request.POST:
		
		form = RSSFeedForm(request.POST, request.FILES, instance=feed)
		
		if form.is_valid():
			form.save()

			return HttpResponseRedirect( reverse('rss_manager:detail', args=[pk])) # Redirect after POST
		
			pass
	else:
		form = RSSFeedForm(instance=feed)

	return render(request, 'rss_manager/rss_feed_form.html', 
			{'form': form, 'feed': feed } )


#
# Add feed to queue
# So a worker will download/read the feed and import/download all new articles
#

def import_feed(request, pk):

	feed = RSS_Feed.objects.get(pk=pk)
	
	# add to queue
	last_imported = datetime.datetime.now()

	from opensemanticetl.tasks import index_rss
	index_rss.apply_async( kwargs={ 'uri': feed.uri }, queue='open_semantic_etl_tasks', priority=5 )

	# save new timestamp
	feed.last_imported = last_imported
	feed.save()

	
	return render(request, 'rss_manager/rss_feed_import.html', {'id': pk,})

#
# Delete feed
#

def delete(request, pk):

	feed = RSS_Feed.objects.get(pk=pk)
	
	feed.delete()

	return redirect('rss_manager:index')


#
# Add all feeds to queue where last import was before configured delta time of the feed
#

def import_feeds(request):

	verbose = True

	log = []
	count = 0
	count_queued = 0

	for feed in RSS_Feed.objects.all():

		count += 1

		if verbose:
			log.append( "Checking delta time of feed: {}".format(feed) ) 


		add_to_queue = True

		# If delta 0, no automatic import
		if not feed.delta:
			add_to_queue = False

		# If delta time, do not import this feed within this time by setting add_to_queue to false
		if feed.delta and feed.last_imported:

			# when next import allowed (because time delta passed)?
			next_import = feed.last_imported + timedelta(minutes=feed.delta)

			# don't check time delta if last import in future (i.e. if system time was wrong)
			if feed.last_imported < timezone.now():			

				# if time for next import not reached, do not index
				if timezone.now() < next_import:
					add_to_queue = False

			if verbose:
				log.append( "Last addition to queue: {}".format(feed.last_imported) )
				log.append( "Next addition to queue: {}".format(next_import) ) 


		if add_to_queue:
			
			if verbose:
				log.append( "Adding feed to queue: {}".format(feed) ) 

			# add to queue
			last_imported = datetime.datetime.now()

			from opensemanticetl.tasks import index_rss
			index_rss.apply_async( kwargs={ 'uri': feed.uri }, queue='open_semantic_etl_tasks', priority=5 )

			# save new timestamp
			feed.last_imported = last_imported
			feed.save()

			count_queued += 1
	
	#
 	# stats / log
 	#
 	
	response = "Feeds to queue: {} of {}".format(count_queued, count)

	if len(log) > 0:
		response += "\n\n" + "\n".join(log)
	
	#
	# return response
	#
	
	status = HttpResponse(response)
	status["Content-Type"] = "text/plain" 
	return status

src/rss_manager/templates/rss_manager/rss_feed_detail.html
{% extends "datasources_base.html" %}

{% block content %}

<div class="row">
	<div class="small-12 columns">

<a class="button small" href="{% url 'rss_manager:index' %}">Feeds (back to list of all newsfeeds)</a>


	</div>
</div>

<div class="row">
	<div class="small-12 columns">

Title or ID:
<h1>{{ rss_feed.title|default:rss_feed.id }}</h1>

	{% if rss_feed.uri %}

	URI: {{ rss_feed.uri }}

	{% endif %}


	{% if rss_feed.description %}

	{{ rss_feed.description }}

	{% endif %}

	</div>
</div>


<div class="row">
	<div class="small-12 columns">

<h3>Actions</h3>


<a class="button" href="{% url 'rss_manager:import_feed' rss_feed.id %}">Import news</a></li>

<a class="button" href="{% url 'rss_manager:update' rss_feed.id %}">Edit settings</a>

<a class="button" href="{% url 'rss_manager:delete' rss_feed.id %}" onclick="return confirm('Are you sure you want to delete this?')">Delete</a>


	</div>
</div>

{% endblock content %}

src/rss_manager/templates/rss_manager/rss_feed_form.html
{% extends "datasources_base.html" %}

{% block content %}

<form {% if form.is_multipart %}enctype="multipart/form-data"{% endif %} action="" method="post">{% csrf_token %}

    {{ form.non_field_errors }}

<div class="row">

	<div class="small-12 columns">


{% if feed.id %}
<h1>Edit RSS newsfeed</h1>
{% else %}
<h1>Add RSS newsfeed</h1>
{% endif %}



	</div>
</div>




<div class="row">

	<div class="small-12 columns">


<dl class="tabs" data-tab>
  <dd><a href="#panel-title">Description (optional)</a></dd>
  <dd class="active"><a href="#panel-datasource">URI</a></dd>
</dl>

	</div>
</div>










<div class="tabs-content">

  <section class="content" id="panel-title">


<div class="row">
	<div class="small-12 columns text-center">
<h2>Name or notes</h2>
	</div>
</div>

<div class="row">
	<div class="small-12 columns">


<p>Not necessary, only for managing purpose</p>

        {{ form.subject.errors }}
        <label for="id_subject">Title:</label>
        {{ form.title }}

<div class="row">

    <div class="small-12 medium-8 columns">
    <h3>Notes</h3>
        {{ form.description.errors }}
        <label for="id_description">Description or Notes</label>
        {{ form.description }}
    </div>


</div>

</section>

  <section class="content active" id="panel-datasource">

<div class="row">

	<div class="small-12 columns text-center">

<h2>URL (Address)</h2>



        {{ form.uri.errors }}
        <label for="id_uri">URI:</label>
        {{ form.uri }}
	<p>For example <i>http://www.opensemanticsearch.org/feed</i></p>


<h2>Frequency (Delta time)</h2>



        {{ form.delta.errors }}
        <label for="id_delta">Delta time (minutes):</label>
        {{ form.delta }}
	<p><i>For example 60 for checking (download) feed every hour</i></p>


    </div>


</div>




</section>





<hr>


<div class="row">
    <div class="small-12 columns">

<h2>Save changes</h2>

    <input class="button" type="submit" value="Save" />



{% if feed.id %}
    <a class="button" href="{% url 'rss_manager:detail' feed.id %}">Cancel</a>
{% else %}
    <a class="button" href="{% url 'rss_manager:index' %}">Cancel</a>
{% endif %}

</div>
</div>

</form>
{% endblock content %}

src/rss_manager/templates/rss_manager/rss_feed_import.html
{% extends "datasources_base.html" %}

{% block content %}

<div class="row">
	<div class="small-12 columns">
<p>Feed added to import queue.</p>
	</div>
</div>

<div class="row">
	<div class="small-12 columns">

<a class="button" href="{% url 'rss_manager:detail' id %}">Back to dataset details</a>
	</div>
</div>

{% endblock content %}

src/rss_manager/templates/rss_manager/rss_feed_list.html
{% extends "datasources_base.html" %}

{% block content %}


<div class="row">
	<div class="small-12 columns">

<br>
	
<ul class="breadcrumbs">
<li><a href="{% url 'datasources:index' %}">Datasources</a></li>
<li><a href="{% url 'rss_manager:index' %}">RSS Newsfeeds</a></li>
 <li class="current"><a href="#">All RSS Newsfeeds</a></li> 
  </ul>

<h1>Newsfeeds</h1>
<p>RSS newsfeeds for import of news</p>

<a class="button" href="{% url 'rss_manager:import_feeds' %}">Check feeds</a>

<a class="button" href="{% url 'rss_manager:create' %}">Add new RSS Feed</a>


	</div>
</div>


<div class="row">
	<div class="small-12 columns">
<h2>All RSS newsfeeds</h2>



{% if rss_feed_list %}
    <ul>
    {% for rss_feed in rss_feed_list %}
        <li><h2><a href="{% url 'rss_manager:detail' rss_feed.id %}">{{ rss_feed.title|default:rss_feed }}</a></h2>
            <a class="button small" href="{% url 'rss_manager:import_feed' rss_feed.id %}">Check for news</a>
            <a class="button small" href="{% url 'rss_manager:detail' rss_feed.id %}">Details</a>
            <a class="button small" href="{% url 'rss_manager:update' rss_feed.id %}">Edit settings</a>
            <a class="button small" href="{% url 'rss_manager:delete' rss_feed.id %}" onclick="return confirm('Are you sure you want to delete this?')">Delete</a>
        </li>
    
    {% endfor %}
    </ul>
{% else %}
    <p>No feeds yet.</p>
{% endif %}


	</div>
</div>


{% endblock content %}

src/rss_manager/templates/rss_manager/rss_manager_import_feeds.html
{% extends "datasources_base.html" %}

{% block content %}

<div class="row">
	<div class="small-12 columns">
<p>Feeds added to queue.</p>
	</div>
</div>

<div class="row">
	<div class="small-12 columns">

<a class="button" href="{% url 'rss_manager:index' %}">Back</a>
	</div>
</div>

{% endblock content %}